imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.lecture_slides: /uploads/files/lecture/slides
    app.path.homework_assignments: /uploads/files/homework/assignments

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
      '%kernel.root_dir%/Resources': AppBundle
    globals:
        gravatar_url: 'https://www.gravatar.com/avatar/'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

vich_uploader:
    db_driver: orm
    mappings:
        lecture_slides:
            uri_prefix: '%app.path.lecture_slides%'
            upload_destination: '%kernel.root_dir%/Resources/uploads/files/lecture/slides'
            namer:              vich_uploader.namer_origname
        work_file:
            uri_prefix: '%app.path.homework_assignments%'
            upload_destination: %kernel.root_dir%/Resources/uploads/files/homework/assignments
            namer:              vich_uploader.namer_origname

easy_admin:
    site_name: '<img src="/assets/img/nfq.png" />'
    design:
        assets:
            css:
                - '/bundles/custom/css/style.css'
        menu:
            - { entity: 'Lecture', label: 'Lectures', icon: 'book', default: true }
            - { entity: 'Homework', label: 'Homework', icon: 'laptop' }
            - { entity: 'News', label: 'News', icon: 'bullhorn' }
            - { entity: 'User', label: 'Users', icon: 'users' }
        brand_color: '#000000'
    list:
        actions:
            - { name: 'show', icon: 'user' }
    entities:
        User:
            controller: AppBundle\Controller\Admin\UserController
            class: AppBundle\Entity\User
            image_base_path: 'https://www.gravatar.com/avatar/'
            form:
                fields:
                    - username
                    - name
                    - { property: 'email', type: 'email', label: 'Email' }
                    - occupation
                    - { property: 'interests', label: 'Programming interests' }
                    - enabled
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_LECTOR': 'ROLE_LECTOR', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            edit:
                form_options: { validation_groups: ['Default'] }
                fields:
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', label: 'New password', type: 'password', type_options: { required: false } }
                    - { property: 'confirmPassword', label: 'Confirm password', type: 'password', type_options: { required: false } }
            new:
                form_options: { validation_groups: ['Default', 'registration'] }
                fields:
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', label: 'Password', type: 'password', type_options: { required: true } }
                    - { property: 'confirmPassword', label: 'Confirm password', type: 'password', type_options: { required: false } }
            list:
                title: 'Users'
                actions: ['show']
                fields:
                    - {property: 'gravatar', type: 'image'}
                    - name
                    - email
                    - role
            show:
                fields:
                    - email
                    - occupation
                    - { property: 'interests', label: 'Programming interests' }
                    - enabled
                    - role
        Lecture:
            controller: AppBundle\Controller\Admin\LectureController
            class: AppBundle\Entity\Lecture
            form:
                fields:
                    - title
                    - description
                    - date
                    - lecturer
            edit:
                form_options: { validation_groups: ['Default'] }
                fields:
                    - { property: 'slidesFile', type: 'vich_file' }
            new:
                form_options: { validation_groups: ['registration'] }
            list:
                title: 'Lectures'
                sort: [ 'date', 'ASC' ]
                actions: ['show']
                fields:
                    - title
                    - date
                    - lecturer
            show:
                fields:
                    - description
                    - date
                    - lecturer
                    - { property: 'slides', template: 'slides.html.twig', base_path: "/admin/download/lecture" }
        Homework:
            controller: AppBundle\Controller\Admin\HomeworkController
            class: AppBundle\Entity\Homework
            access_role: ROLE_LECTOR
            form:
                fields:
                    - title
                    - description
                    - dueDate
                    - lecturer
            edit:
                form_options: { validation_groups: ['Default'] }
            new:
                form_options: { validation_groups: ['registration'] }
            list:
                sort: [ 'dueDate', 'ASC' ]
                actions: ['show']
                fields:
                    - title
                    - dueDate
                    - lecturer
            show:
                fields:
                    - description
                    - dueDate
                    - lecturer

        Assignment:
            controller: AppBundle\Controller\Admin\AssignmentController
            class: AppBundle\Entity\Assignment
            access_role: ROLE_USER
            disabled_actions: ['new', 'list', 'edit', 'delete']
            show:
                fields:
                    - homework
                    - student
                    - date
                    - { property: 'work', template: 'work.html.twig', base_path: "/admin/download/homework" }
                    - grade
        News:
            controller: AppBundle\Controller\Admin\NewsController
            class: AppBundle\Entity\News
            access_role: ROLE_LECTOR
            edit:
                form_options: { validation_groups: ['Default'] }
                fields:
                    - title
                    - description
                    - date
                    - author
            new:
                form_options: { validation_groups: ['registration'] }
                fields:
                    - title
                    - description
                    - date
                    - author
            list:
                actions: ['show']
                sort: [ 'date', 'ASC' ]
                fields:
                    - title
                    - date
                    - author
            show:
                fields:
                    - description
                    - date
                    - author
        Comment:
            controller: AppBundle\Controller\Admin\CommentController
            class: AppBundle\Entity\Comment
            access_role: ROLE_USER
            edit:
                form_options: { validation_groups: ['Default'] }
                fields:
                    - content
                    - date
                    - author
            new:
                form_options: { validation_groups: ['registration'] }
                fields:
                    - content
                    - date
                    - author
            list:
                sort: [ 'date', 'ASC' ]
                actions: ['show']
                fields:
                    - newsId
                    - content
                    - author
                    - date
            show:
                fields:
                    - newsId
                    - content
                    - author
                    - date
