imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            channels: ['!event', '!doctrine']
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']

easy_admin:
    design:
        menu:
            - User
            - Lecture
            - Homework
            - News
            - CommentThread
            - Comment
    entities:
        User:
            controller: AppBundle\Controller\Admin\UserController
            class: AppBundle\Entity\User
            form:
                fields:
                    - username
                    - name
                    - { property: 'email', type: 'email', label: 'Email' }
                    - enabled
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_LECTOR': 'ROLE_LECTOR', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            edit:
                form_options: { validation_groups: ['Default'] }
                fields:
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', label: 'New password', type: 'password', type_options: { required: false } }
                    - { property: 'confirmPassword', label: 'Confirm password', type: 'password', type_options: { required: false } }
            new:
                form_options: { validation_groups: ['Default', 'registration'] }
                fields:
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', label: 'Password', type: 'password', type_options: { required: true } }
                    - { property: 'confirmPassword', label: 'Confirm password', type: 'password', type_options: { required: false } }
            list:
                actions: ['show']
                fields:
                    - id
                    - name
                    - email
                    - roles
            show:
                fields:
                    - username
                    - name
                    - email
                    - enabled
                    - roles
        News:
            controller: AppBundle\Controller\Admin\NewsController
            class: AppBundle\Entity\News
            access_role: ROLE_LECTOR
            form:
                fields:
                    - title
                    - description
                    - date
                    - author
            edit:
                form_options: { validation_groups: ['Default'] }
            new:
                form_options: { validation_groups: ['registration'] }
            list:
                actions: ['show']
                sort: [ 'date', 'ASC' ]
                fields:
                    - id
                    - thread
                    - title
                    - date
                    - author
            show:
                fields:
                    - title
                    - description
                    - date
                    - author
        Comment:
            controller: AppBundle\Controller\Admin\CommentController
            class: AppBundle\Entity\Comment
            access_role: ROLE_USER
            disabled_actions: ['new']
            form:
                fields:
                    - content
            edit:
                form_options: { validation_groups: ['Default'] }
            new:
                form_options: { validation_groups: ['registration'] }
            list:
                sort: [ 'date', 'ASC' ]
                actions: ['show']
                fields:
                    - id
                    - thread
                    - content
                    - author
                    - date
            show:
                fields:
                    - id
                    - thread
                    - content
                    - author
                    - date
        CommentThread:
            controller:
            class: AppBundle\Entity\CommentThread
            disabled_actions: ['new']
            list:
                actions: ['show']
                fields:
                    - id
                    - owner_name
                    - comments
            show:
                fields:
                    - id
                    - owner_name
                    - comments
