imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            channels: ['!event', '!doctrine']
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']

easy_admin:
    design:
        menu:
            - CommentThread
            - Comment
    entities:
        Comment:
            controller: AppBundle\Controller\Admin\CommentController
            class: AppBundle\Entity\Comment
            access_role: ROLE_USER
            form:
                fields:
                    - content
                    - date
                    - author
            edit:
                form_options: { validation_groups: ['Default'] }
            new:
                form_options: { validation_groups: ['registration'] }
            list:
                sort: [ 'date', 'ASC' ]
                actions: ['show']
                fields:
                    - content
                    - author
                    - date
            show:
                fields:
                    - content
                    - author
                    - date
        CommentThread:
            controller:
            class: AppBundle\Entity\CommentThread
            disabled_actions: ['new']
            list:
                actions: ['show']
                fields:
                    - id
                    - owner_name
                    - comments
            show:
                fields:
                    - id
                    - owner_name
                    - comments
