# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.user_voter:
        class: AppBundle\Security\UserVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    app.lecture_voter:
        class: AppBundle\Security\LectureVoter
        tags:
        - { name: security.voter }
        # small performance boost
        public: false
    app.homework_voter:
        class: AppBundle\Security\HomeworkVoter
            - { name: security.voter }
        # small performance boost
        public: false
    app.news_voter:
        class: AppBundle\Security\NewsVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    app.comment_voter:
        class: AppBundle\Security\CommentVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    app.assignment_voter:
            class: AppBundle\Security\AssignmentVoter
            tags:
                - { name: security.voter }
            # small performance boost
            public: false
    app.twig_extension:
            class: AppBundle\Twig\AppExtension
            public: false
            tags:
                - { name: twig.extension }
